[package]
name = "poly-feeds"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
poly-domain = { workspace = true }
poly-config = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
chainlink-data-streams-sdk = { workspace = true }
chainlink-data-streams-report = { workspace = true }
